// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVaVgpR7U7CX_tpy1688iuWVc0f7by-Q',
    appId: '1:378126890521:web:35100e914a1bb66fe01c88',
    messagingSenderId: '378126890521',
    projectId: 'receipe-42d42',
    authDomain: 'receipe-42d42.firebaseapp.com',
    storageBucket: 'receipe-42d42.appspot.com',
    measurementId: 'G-VV31EET5SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGDJYnvniqFQQxB9xFJ9Jusj4drg7duwo',
    appId: '1:378126890521:android:f5ca69efd1ee85d6e01c88',
    messagingSenderId: '378126890521',
    projectId: 'receipe-42d42',
    storageBucket: 'receipe-42d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmGD2CMJuEdn2eyoRiGaF5uVZSqlyIOs',
    appId: '1:378126890521:ios:302599bf9e91e193e01c88',
    messagingSenderId: '378126890521',
    projectId: 'receipe-42d42',
    storageBucket: 'receipe-42d42.appspot.com',
    iosClientId: '378126890521-pf21a1dfhtc06ipognafjsehcgmv51h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bismillah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmGD2CMJuEdn2eyoRiGaF5uVZSqlyIOs',
    appId: '1:378126890521:ios:302599bf9e91e193e01c88',
    messagingSenderId: '378126890521',
    projectId: 'receipe-42d42',
    storageBucket: 'receipe-42d42.appspot.com',
    iosClientId: '378126890521-pf21a1dfhtc06ipognafjsehcgmv51h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bismillah',
  );
}
